appName: keus-samsung-tv-controller
displayName: "Keus Samsung TV Controller"
description: "OAuth-enabled app for controlling Samsung TVs via SmartThings API"
appType: WEBAPP_SMARTAPP
singleInstance: true
classifications:
  - CONNECTED_SERVICE
oauth:
  clientName: "Keus TV Controller"
  scope:
    - "r:devices:*"
    - "x:devices:*"
  redirectUris:
    - "https://samsung-keus.onrender.com/callback"
ui:
  pluginId: ""
  pluginUri: ""
  dashboardCardsEnabled: false
  preInstallDashboardCardsEnabled: false
webhookSmartApp:
  targetUrl: "https://samsung-keus.onrender.com/webhook"
  publicKey: ""
